spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dborlik.cjmn080aizuq.us-east-2.rds.amazonaws.com/OrlikDB
    username: orlikAdmin
    password: AWSorlik1
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
server:
  port: 5000